branch-defaults:
  default:
    environment: mySite-env
    group_suffix: null
  main:
    environment: mySite-env
    group_suffix: null
environment-defaults:
  mySite-env:
    branch: null
    repository: null
global:
  application_name: mySite
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
